import type { Modality, Testimonial, Plan, Unit } from './index';

// Central de Dados (Simula o futuro CMS/Banco de Dados)

export const modalitiesData: Modality[] = [
  {
    id: 'musculacao',
    title: 'Musculação',
    description: 'Equipamentos importados com biomecânica perfeita para o seu shape.',
    imageUrl: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cross-training',
    title: 'Cross Training',
    description: 'Box oficial para treinos de alta intensidade, LPO e condicionamento.',
    imageUrl: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'fight-club',
    title: 'Fight Club',
    description: 'Octógono e tatame para Boxe, Muay Thai e Jiu-Jitsu de alto nível.',
    imageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'cardio-hitech',
    title: 'Cardio Hi-Tech',
    description: 'Equipamentos com telas touch, percursos virtuais e monitoramento.',
    imageUrl: 'https://images.unsplash.com/photo-1518611012118-696072aa579a?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
  },
];

export const testimonialsData: Testimonial[] = [
  {
    id: 't1',
    name: 'Rafael S.',
    text: '"Estrutura impecável. O maquinário é importado, a iluminação te deixa no clima do treino e o reconhecimento facial na entrada é super prático."',
    avatarUrl: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    offsetClass: '',
  },
  {
    id: 't2',
    name: 'Carlos M.',
    text: '"A melhor academia da região, sem dúvidas. Os professores realmente corrigem sua postura e o App monta um treino que te tira da zona de conforto."',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    offsetClass: 'md:mt-8',
  },
  {
    id: 't3',
    name: 'Mariana C.',
    text: '"Treinava em outra rede e mudei pra ForBody pela vibe. O ambiente é focado em resultado, surreal. E a arena de lutas é fantástica!"',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    rating: 5,
    offsetClass: 'md:mt-16',
  },
];

export const plansData: Plan[] = [
  {
    id: 'basic',
    name: 'Plano Basic',
    description: 'O essencial para o seu treino diário com acesso total à área de musculação.',
    price: 99.90,
    originalPrice: 139.90,
    priceSuffix: '/mês',
    features: ['Acesso total à musculação', 'Acesso em horário livre', 'App ForBody (Acesso padrão)'],
    ctaText: 'Assinar Basic',
    checkoutUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/2/page/landing-page',
  },
  {
    id: 'red',
    name: 'Plano RED',
    description: 'Acesso ilimitado a todo o ecossistema, incluindo lutas e cadeira de massagem.',
    isHighlighted: true,
    highlightBadge: 'Pacote 12 Meses',
    price: 79.90,
    installments: 12,
    priceDisclaimer: 's/ juros no cartão',
    features: ['Acesso a qualquer unidade da rede', 'Livre acesso a Lutas e Modalidades', 'Cadeira de massagem pós-treino', 'Leve 5 amigos por mês para treinar'],
    ctaText: 'Assinar RED Agora',
    checkoutUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/2/page/landing-page',
  },
];

export const unitsData: Unit[] = [
  {
    id: 'u-triunfo',
    slug: 'triunfo',
    name: 'Triunfo',
    state: 'SP',
    evoId: 1,
    evoUnitId: 1,
    salesUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/1/site/QhXXzoY7OMy%5BPLUS%5DFpULG15Wrw%5BEQUAL%5D%5BEQUAL%5D',
    studentAreaUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/1/page/landing-page/login',
    locationUrl: 'https://share.google/sKVYOtlnOWU3BY13D',
    status: 'active',
    googleReviewsScore: 4.7,
    googleReviewsCount: 48,
    city: 'Ribeirão Preto',
    address: 'R. Triunfo, 385 - Santa Cruz do Jose Jacques, Ribeirão Preto - SP',
    whatsapp: '16970000001',
    instagram: '@forbody.triunfo',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    googlePlaceId: 'ChIJXZTIhbq_uZQRvvgjq08MRcc'
  },
  {
    id: 'u-barao',
    slug: 'barao-do-bananal',
    name: 'Barão do Bananal',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 2,
    evoUnitId: 2,
    salesUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/2/site/%5BPLUS%5DeIL%5BPLUS%5DfzZNcy7Gt%5BBAR%5DPl5KIrQ%5BEQUAL%5D%5BEQUAL%5D',
    studentAreaUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/2/page/landing-page/login',
    locationUrl: 'https://share.google/ENEFKsmVe38liffSV',
    status: 'active',
    googleReviewsScore: 4.6,
    googleReviewsCount: 30,
    address: 'Av. Barão do Bananal, 820 - Chácara São João, Ribeirão Preto - SP',
    whatsapp: '16970000002',
    instagram: '@forbody.barao',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    googlePlaceId: 'ChIJwVOXprm_uZQREFsgGHIf8y4'
  },
  {
    id: 'u-vila-virginia',
    slug: 'vila-virginia',
    name: 'Vila Virgínia',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 3,
    evoUnitId: 3,
    salesUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/3/page/landing-page',
    studentAreaUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/3/page/landing-page/login',
    locationUrl: 'https://share.google/k2JOHjzjGax70I28E',
    status: 'active',
    googleReviewsScore: 4.5,
    googleReviewsCount: 25,
    address: 'R. Franco da Rocha, 1370 - Vila Virginia, Ribeirão Preto - SP',
    whatsapp: '16970000003',
    instagram: '@forbody.vilavirg',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    googlePlaceId: 'ChIJjx8pfwC_uZQRt8MeuNMo8aA'
  },
  {
    id: 'u-portinari',
    slug: 'portinari',
    name: 'Portinari',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 4,
    evoUnitId: 4,
    salesUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/4/site/82pusjWxF6YoZfqAbFmy5A%5BEQUAL%5D%5BEQUAL%5D',
    studentAreaUrl: 'https://evo-totem.w12app.com.br/fourbodyacademia/4/page/landing-page/login',
    locationUrl: 'https://share.google/lSkCXu0Zugy44eidZ',
    status: 'active',
    googleReviewsScore: 4.4,
    googleReviewsCount: 18,
    address: 'Av. Nelson Ferreira De Melo, 365 - Candido Portinari, Ribeirão Preto - SP',
    whatsapp: '16970000004',
    instagram: '@forbody.portinari',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    googlePlaceId: 'ChIJNegEDqjBuZQRsXJxQT9NpTo'
  },
  {
    id: 'u-nova-rp-1',
    slug: 'nova-unidade-ribeirao-preto-1',
    name: 'Nova Unidade Ribeirão Preto 1',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 0,
    evoUnitId: undefined,
    salesUrl: '#',
    studentAreaUrl: '#',
    status: 'coming_soon',
    googleReviewsScore: 0,
    googleReviewsCount: 0,
    address: 'Endereço em breve',
    whatsapp: '',
    instagram: '',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    locationUrl: '#',
    googlePlaceId: ''
  },
  {
    id: 'u-nova-rp-2',
    slug: 'nova-unidade-ribeirao-preto-2',
    name: 'Nova Unidade Ribeirão Preto 2',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 0,
    evoUnitId: undefined,
    salesUrl: '#',
    studentAreaUrl: '#',
    status: 'coming_soon',
    googleReviewsScore: 0,
    googleReviewsCount: 0,
    address: 'Endereço em breve',
    whatsapp: '',
    instagram: '',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    locationUrl: '#',
    googlePlaceId: ''
  },
  {
    id: 'u-nova-rp-3',
    slug: 'nova-unidade-ribeirao-preto-3',
    name: 'Nova Unidade Ribeirão Preto 3',
    city: 'Ribeirão Preto',
    state: 'SP',
    evoId: 0,
    evoUnitId: undefined,
    salesUrl: '#',
    studentAreaUrl: '#',
    status: 'coming_soon',
    googleReviewsScore: 0,
    googleReviewsCount: 0,
    address: 'Endereço em breve',
    whatsapp: '',
    instagram: '',
    mapEmbedUrl: '',
    businessHours: [],
    galleryUrls: [],
    teachers: [],
    locationUrl: '#',
    googlePlaceId: ''
  }
];