-- OBSOLETO: este arquivo era um rascunho antigo e estava inconsistente.
-- Não executar este arquivo no Supabase.
--
-- Schema canônico atual:
-- src/20240101000000_create_units.sql
--
-- Motivo:
-- 1. O rascunho anterior tinha fechamento extra de parêntese.
-- 2. Duplicava a tabela units com risco de divergência.
-- 3. O projeto agora usa como referência oficial o SQL versionado em src/.
